import React from "react";

const CoreSystemComponenets = () => {
  return (
    <section className="core-system-section">
      <div className="container">
        
        <h2 className="core-title">Core Systems Components</h2>
        <p className="core-desc">
          Our wave power system is built using advanced, reliable components
          that work together to efficiently convert ocean wave motion into
          clean and sustainable electricity.
        </p>

         
        <div className="row mt-5">
           
          <div className="col-lg-6">
            <div className="core-item">
              <h5>Wave Energy Converter (WEC)</h5>
              <p>
                The Wave Energy Converter is the heart of our wave power
                system. It captures the natural motion of ocean waves
                and converts it into usable mechanical energy.
              </p>
            </div>

            <div className="core-item mt-4">
              <h5>Control & Monitoring System</h5>
              <p>
                Our intelligent control and monitoring system continuously
                tracks system conditions, ensuring optimal performance
                and operational safety.
              </p>
            </div>
          </div>

          
          <div className="col-lg-6">
            <div className="core-item">
              <h5>Power Take-Off (PTO) System</h5>
              <p>
                The Power Take-Off system converts the mechanical energy
                generated by wave motion into electrical energy
                through advanced conversion technologies.
              </p>
            </div>

            <div className="core-item mt-4">
              <h5>Advanced Grid Integration (GI)</h5>
              <p>
                The grid integration system ensures that the generated
                electricity is safely and efficiently delivered
                to the power grid.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default CoreSystemComponenets;
